# Cloud Build config that injects GEMINI_API_KEY from Secret Manager into the
# frontend build so mic/speaker (Live tutor + TTS) work in the deployed app.
#
# Prerequisites:
# 1. Create secret: Secret Manager → Create secret "GEMINI_API_KEY" with your Gemini API key.
# 2. Grant Cloud Build access: IAM → find "Cloud Build Service Account" (e.g. PROJECT_NUMBER@cloudbuild.gserviceaccount.com)
#    → add role "Secret Manager Secret Accessor" (or grant on the secret).
#
# Deploy:
#   gcloud build submit --config=cloudbuild.yaml .
#
# Optional: set region when submitting
#   gcloud build submit --config=cloudbuild.yaml . --substitutions=_REGION=eu-west1

substitutions:
  _REGION: us-central1
  _SERVICE: lingo

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg VITE_GEMINI_API_KEY=$$VITE_GEMINI_API_KEY \
          -t gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA} \
          -t gcr.io/${PROJECT_ID}/${_SERVICE}:latest \
          .
    secretEnv: ['VITE_GEMINI_API_KEY']

  - name: 'gcr.io/cloud-builders/docker'
    id: push
    args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA}']
    waitFor: ['build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image=gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
    waitFor: ['push']

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/GEMINI_API_KEY/versions/latest
      env: 'VITE_GEMINI_API_KEY'

images:
  - 'gcr.io/${PROJECT_ID}/${_SERVICE}:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/${_SERVICE}:latest'
